trigger:
  branches:
    include:
      - '*'  # Trigger on all branches

schedules:
- cron: "*/15 * * * *"
  displayName: Every 15 minutes

jobs:
- job: MergeBasedOnCommitMessage
  displayName: Merge Based on Commit Message
  steps:
  - checkout: self

  - script: |
      # Fetch the latest changes from the repository
      git fetch origin

      # Loop through branches
      for branch in $(git for-each-ref --format="%(refname:short)" refs/heads/); do
        # Create an associative array to store commit timestamps
        declare -A timestamps

        # Loop through commits on the branch
        for commit in $(git log --pretty=format:"%H %s %at" origin/$branch..$branch); do
          commit_hash=$(echo $commit | awk '{print $1}')
          commit_message=$(echo $commit | awk '{$1=$2=""; print $0}')
          commit_timestamp=$(echo $commit | awk '{print $3}')
          
          # Check if commit message starts with "GH" or "RW"
          if [[ $commit_message =~ ^(GH|RW)\| ]]; then
            target_branch="${BASH_REMATCH[1]}"
            
            # Compare and store the latest commit timestamp
            if [[ ${timestamps[$target_branch]+_} && $commit_timestamp -gt ${timestamps[$target_branch]} ]]; then
              timestamps["$target_branch"]=$commit_timestamp
              latest_commit_hash["$target_branch"]=$commit_hash
            elif ! [[ ${timestamps[$target_branch]+_} ]]; then
              timestamps["$target_branch"]=$commit_timestamp
              latest_commit_hash["$target_branch"]=$commit_hash
            fi
          fi
        done

        # Merge the latest commit into the corresponding branch
        if [[ ${latest_commit_hash["GH"]+_} && $branch == "GH_DEV_RISHI" ]]; then
          git checkout GH_DEV_RISHI
          git merge --no-ff ${latest_commit_hash["GH"]}
          git push
        fi

        if [[ ${latest_commit_hash["RW"]+_} && $branch == "RW_DEV_RISHI" ]]; then
          git checkout RW_DEV_RISHI
          git merge --no-ff ${latest_commit_hash["RW"]}
          git push
        fi
      done
    displayName: 'Merge Based on Commit Message'